[tool.poetry]
name = "dke2023"
version = "0.1.0"
description = ""
authors = ["Alex <paracosm17@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"
django = "^5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
